[workspace]
package.authors = ["Luca Goslar <luca@zugriff.eu>"]
members = ["crates/zugriff"]
resolver = "2"

[workspace.dependencies]
actix-web = "= 4.5.1"
tokio = "= 1.37.0"
awc = "= 3.4.0"
clap = "= 4.5.4"
human-panic = "= 2.0.0"
which = "= 6.0.1"
indicatif = "= 0.17.8"
dialoguer = "= 0.11.0"
strum_macros = "= 0.26.2"
tempfile = "= 3.10.1"
tar = "= 0.4.40"
flate2 = "= 1.0.30"
directories = "= 5.0.1"
path-absolutize = "= 3.1.1"
once_cell = "= 1.19.0"
regex = "= 1.10.4"
hotwatch = "= 0.5.0"
zip = "= 1.2.3"
xz2 = "= 0.1.7"
serde_json = "= 1.0.117"
serde = "= 1.0.201"
dotenvy = "= 0.15.7"
url = "= 2.5.0"
futures = "= 0.3.30"
bytes = "= 1.6.0"
bincode = "= 1.3.3"
serde-envfile = "= 0.1.0"
env_logger = "= 0.11.3"
log = "= 0.4.21"
garde = "= 0.18.0"
size = "= 0.4.1"
colored = "= 2.1.0"
anyhow = "= 1.0.83"
fs_extra = "= 1.3.0"
symlink = { git = "https://gitlab.com/chris-morgan/symlink.git", version = "= 0.1.0" }
serde_with = "= 3.8.1"
async-signal = "= 0.2.6"
signal-hook = "= 0.3.17"
