[workspace]
package.authors = ["Luca Goslar <luca@zugriff.eu>"]
members = ["crates/zugriff"]
resolver = "2"

[workspace.dependencies]
actix-web = "= 4.8.0"
tokio = "= 1.38.0"
awc = "= 3.5.0"
clap = "= 4.5.26"
human-panic = "= 2.0.2"
which = "= 7.0.1"
indicatif = "= 0.17.9"
dialoguer = "= 0.11.0"
strum = "= 0.26.3"
strum_macros = "= 0.26.4"
tempfile = "= 3.15.0"
tar = "= 0.4.43"
flate2 = "= 1.0.35"
directories = "= 6.0.0"
path-absolutize = "= 3.1.1"
once_cell = "= 1.20.2"
regex = "= 1.11.1"
hotwatch = "= 0.5.0"
zip = "= 2.2.2"
serde_json = "= 1.0.135"
serde = "= 1.0.217"
dotenvy = "= 0.15.7"
url = "= 2.5.4"
futures = "= 0.3.30"
bytes = "= 1.9.0"
bincode = "= 1.3.3"
serde-envfile = "= 0.1.0"
env_logger = "= 0.11.6"
log = "= 0.4.25"
garde = "= 0.21.1"
size = "= 0.4.1"
colored = "= 3.0.0"
anyhow = "= 1.0.95"
fs_extra = "= 1.3.0"
symlink = { git = "https://gitlab.com/chris-morgan/symlink.git", version = "= 0.1.0", rev = "dcc8849be3e8599c398361a487d22829307bef14" }
serde_with = "= 3.12.0"
async-signal = "= 0.2.10"
signal-hook = "= 0.3.17"
sha3 = "= 0.10.8"
base64 = "= 0.22.1"