version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - 6379:6379
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=zugriff
