name: 'zugriff: Deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/**

jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - './apps/docs/**'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - run: echo "ZUGRIFF_SKIP_POSTINSTALL=true" >> $GITHUB_ENV
      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - name: Extract Most Recent Commit Message
        run: |
          echo "COMMIT_MESSAGE=$(git log --pretty=oneline --abbrev-commit | head -n 1 | cut -c 1-128)" >> $GITHUB_ENV

      - uses: zugriffcloud/action-deploy@latest
        if: steps.filter.outputs.docs == 'true'
        with:
          cwd: ./apps/docs
          name: ${{ env.COMMIT_MESSAGE }}
          deploymentToken: ${{ secrets.ZUGRIFF_TOKEN_DOCS }}
          promotions: |
            production
