name: 'JavaScript: Changesets'

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'JavaScript: Test'
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - run: export ZUGRIFF_SKIP_POSTINSTALL=true
      - run: pnpm install --frozen-lockfile

      - uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: 'chore: bump versions'
          title: 'chore: bump versions'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
